// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKEsRltZ55xDoljFBGApJFj-r2i-f8vEo',
    appId: '1:580255372158:web:e9352c2c27964cc599592f',
    messagingSenderId: '580255372158',
    projectId: 'trabajos24-5c0de',
    authDomain: 'trabajos24-5c0de.firebaseapp.com',
    storageBucket: 'trabajos24-5c0de.appspot.com',
    measurementId: 'G-0J0LK1W1WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWdIy_2Kk6gyWQj-tU3oi9m4ILRaepmE',
    appId: '1:580255372158:android:3945964f07e6d75b99592f',
    messagingSenderId: '580255372158',
    projectId: 'trabajos24-5c0de',
    storageBucket: 'trabajos24-5c0de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0heHJBhnXy5oauj9txsRW5ytH_i0n_Q',
    appId: '1:580255372158:ios:ca51f14ef14be7af99592f',
    messagingSenderId: '580255372158',
    projectId: 'trabajos24-5c0de',
    storageBucket: 'trabajos24-5c0de.appspot.com',
    iosClientId: '580255372158-2uimm7da18ukv17dvti7n8k560571mp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsapp',
  );
}
